#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'AzorFabricio'
        hostname: AzorFabricio-67992559115
        username: azorfabricio
        password: '$6$n4WIWVvGEZ.XkLLE$5xae2H8qXCArHy14sgYlNJLqhXOXsm2HdmPvmgCThRaM9KtG8X6lyvN4j/zoyKXLT78CHjDSiO0ssB3gupo.F/'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Campo_Grande"
    storage:
    layout:
      name: lvm
      sizing-policy: all
    packages:
        - libreoffice
        - gimp
        - vlc
        - ufw
        - kdenlive
        - inkscape
        - gdebi
    snaps:
        - name: spotify
          channel: stable
          classic: false
        - name: brave
        - name: clapper
        - name: clapper
        - name: telegram-desktop
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
